
ARG BASEIMAGE="mcr.microsoft.com/devcontainers/base:debian"
FROM ${BASEIMAGE}
ARG CC="gcc"
ARG CXX="g++"
ARG FC="gfortran"
ARG WORKDIR="/work"
ARG BUILDDIR="build-dev"
ARG BUILDTYPE="Debug"
WORKDIR ${WORKDIR}

ENV MINIFORGE_SRC_DIR="https://github.com/conda-forge/miniforge/releases/latest/download"
ENV INSTALLDIR=${BUILDDIR}/install

# Copy arguments to variables so they're available in the container
ENV CC=${CC} \
    CXX=${CXX} \
    FC=${FC} \
    WORKDIR=${WORKDIR} \
    BUILDDIR=${BUILDDIR} \
    BUILDTYPE=${BUILDTYPE}

RUN if command -v 'apt-get'; then \
      apt-get update && apt-get install -y --no-install-recommends \
        bash \
        binutils \
        ca-certificates \
        clang \
        git \
        m4 \
        make \
        vim \
        wget; \
    fi \
    && mkdir -p ./miniforge \
    && wget -O ./miniforge.sh "${MINIFORGE_SRC_DIR}/Miniforge3-$(uname)-$(uname -m).sh" \
    && bash ./miniforge.sh -b -u -p ${WORKDIR}/miniforge \
    && rm miniforge.sh
ENV PATH=${WORKDIR}/miniforge/envs/cea-dev/lib:${WORKDIR}/miniforge/bin:${WORKDIR}/miniforge/lib:$PATH
RUN conda init --all
